FROM likask/mofem-spack-build

LABEL maintainer="Lukasz.Kaczmarczyk@glasgow.ac.uk"

WORKDIR $MOFEM_INSTALL_DIR

# image run hook: the -l will make sure /etc/profile environments are loaded
CMD        /bin/bash -l

