FROM likask/ubuntu_mofem

MAINTAINER Lukasz.Kaczmarczyk@glasgow.ac.uk

ADD mofem /mofem
RUN /mofem/docker_build_mofem_script.sh

VOLUME /mofem_build
WORKDIR /mofem_build

CMD /mofem/docker_build_mofem_script.sh
