FROM likask/mofem-spack-env:latest

LABEL maintainer="Lukasz.Kaczmarczyk@glasgow.ac.uk"

ADD . $MOFEM_SRC_DIR/

# Install core library
RUN . $SPACK_ROOT_DIR/share/spack/setup-env.sh && \
  spack dev-build \
  --source-path $MOFEM_SRC_DIR \
  --keep-prefix \
  --test root \
  mofem-cephas@develop~copy_user_modules+docker build_type=Release ^petsc+X && \
  MOFEM_CEPHAS_HASH=`spack find -lv mofem-cephas | awk '/mofem-cephas/ {print $1}' | head -n 1` && \
  echo "export MOFEM_CEPHAS_HASH=$MOFEM_CEPHAS_HASH" >> ~/.bashrc && \
  cd $MOFEM_INSTALL_DIR/core-build-Release-$MOFEM_CEPHAS_HASH && make clean 
  
# Install users mdoules
RUN . $SPACK_ROOT_DIR/share/spack/setup-env.sh && \
  MOFEM_CEPHAS_HASH=`spack find -lv mofem-cephas | awk '/mofem-cephas/ {print $1}' | head -n 1` && \
  spack dev-build \
  --test root  \
  --source-pat $MOFEM_UM_SRC_DIR \
  mofem-users-modules@develop+docker build_type=Release \
  ^/$MOFEM_CEPHAS_HASH && \
  MOFEM_UM_HASH=`spack find -lv mofem-users-modules | awk '/mofem-users-modules/ {print $1}' | head -n 1` && \
  cd $MOFEM_INSTALL_DIR/um-build-Release-$MOFEM_UM_HASH && make clean && \
  spack view symlink -i $MOFEM_INSTALL_DIR/um_view /$MOFEM_UM_HASH && \
  echo "export MOFEM_UM_HASH=$MOFEM_UM_HASH" >> ~/.bashrc && \
  echo "export PATH=$MOFEM_INSTALL_DIR/um_view/bin:$PATH" >> ~/.bashrc 

VOLUME $MOFEM_INSTALL_DIR
WORKDIR $MOFEM_INSTALL_DIR

# image run hook: the -l will make sure /etc/profile environments are loaded
CMD        /bin/bash -l



