FROM ubuntu:precise

MAINTAINER Lukasz.Kaczmarczyk@glasgow.ac.uk

ADD mofem /mofem

# Set environment
ENV BUILD_DIR /build_mofem_precise
ENV MOFEM_SRC_DIR /mofem/
ENV MOFEM_BUILD_DIR $BUILD_DIR/lib
ENV MOFEM_INSTALL_DIR $BUILD_DIR/um

ENV PETSC_VERSION 3.6.3
ENV PETSC_DIR=/opt/petsc
ENV PETSC_ARCH=arch-linux2-c-opt
ENV PATH $PATH:$PETSC_DIR/$PETSC_ARCH/bin

ENV BUILD_TYPE=MinSizeRel
ENV CMAKE /opt/local/bin/cmake
ENV CTEST /opt/local/bin/ctest

RUN apt-get update \
&& apt-get install -y \
build-essential \
gcc \
g++ \
libopenmpi-dev \
openmpi-bin \
openssh-server \
libblas-dev \
liblapack-dev \
&& rm -rf /var/lib/apt/lists/*

RUN wget https://www.dropbox.com/s/ll3g2drxvmk9ul9/mofem_env.tar.gz \
&& tar -xzf mofem_env.tar.gz \
&& rm -f mofem_env.tar.gz

# RUN echo 'root:mofem' | chpasswd \
# && adduser -q developer \
# && mkdir $BUILD_DIR \
# && chown developer $BUILD_DIR
# USER developer

RUN mkdir -p $MOFEM_BUILD_DIR \
&& cd $MOFEM_BUILD_DIR \
&& $CMAKE \
-DCMAKE_BUILD_TYPE=MinSizeRel \
-DBUILD_SHARED_LIBS=1 \
-DCMAKE_CXX_FLAGS="-Wall" \
-DPETSC_DIR=$PETSC_DIR \
-DPETSC_ARCH=$PETSC_ARCH \
-DMOAB_DIR=$PETSC_DIR/$PETSC_ARCH \
-DWITH_ADOL-C=1 \
-DCMAKE_INSTALL_PREFIX=$MOFEM_INSTALL_DIR \
$MOFEM_SRC_DIR \
&& cd $MOFEM_BUILD_DIR \
&& make install \
&& $CTEST --output-on-failure -D Experimental \
&& make clean \
&& cd $MOFEM_INSTALL_DIR  \
&& $CMAKE -DCMAKE_CXX_FLAGS="-Wall" users_modules \
&& make \
&& $CTEST --output-on-failure -D Experimental \
&& make clean
