FROM likask/mofem_build:latest

MAINTAINER Lukasz.Kaczmarczyk@glasgow.ac.uk

# Build argumnets
ARG MODULE
ARG NBPROCS

# Envirionment
ENV MODULE_SRC_DIR $MOFEM_SRC_DIR/users_modules/$MODULE
ENV MODULE_BUILD_DIR $MOFEM_INSTALL_DIR/$MODULE
ENV CMAKE_OPTIONS -DBUILD_SHARED_LIBS=yes -DCMAKE_CXX_FLAGS="-Wall"

# Usually do not change this
ADD mofem/users_modules/$MODULE $MOFEM_SRC_DIR/users_modules/$MODULE

WORKDIR $MODULE_BUILD_DIR
CMD \
cd $MOFEM_INSTALL_DIR && /opt/local/bin/cmake $CMAKE_OPTIONS users_modules && \
if [ -e $MODULE_BUILD_DIR/Makefile ]; then \
  cd $MODULE_BUILD_DIR && make -j $NBPROCS && ctest; \
elif [ -e $MODULE_BUILD_DIR/atom_tests/Makefile ]; then \
  cd $MODULE_BUILD_DIR/atom_tests && make -j $NBPROCS && ctest; \
else echo "AAA"; \
fi
