FROM jenkins/jenkins:lts
# if we want to install via apt
USER root

# Install packages
RUN apt-get update && \
apt-get install -y \
file \
zlib1g-dev \
openssh-server \
wget \
valgrind \
curl \
git \
g++ \
gfortran \
gdb \
m4 \
automake \
build-essential \
libtool \
libblas-dev \
liblapack-dev \
libsigsegv2 \
libjpeg-dev \
graphviz \
doxygen \
cmake \
pkg-config \
gnuplot \
pstack \
ca-certificates \
python \
python3-distutils \
libx11-dev \
xauth \
xterm \
unzip \
mesa-common-dev \
libglu1-mesa-dev \
libxmu-dev \
libxi-dev \
libssl-dev \
gawk \
&& rm -rf /var/lib/apt/lists/*

# drop back to the regular jenkins user - good practice
USER jenkins
