FROM ubuntu:precise

MAINTAINER Lukasz.Kaczmarczyk@glasgow.ac.uk

# Confif apt-get
RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99local

# Install packages
RUN apt-get update && \
apt-get install -y \
file \
zlib1g-dev \
wget \
git \
g++ \
m4 \
automake \
build-essential \
libtool \
cmake \
ca-certificates \
python \
bison \
flex \
libx11-dev \
xauth \
xterm \
libbz2-dev \
openssh-server \
libopenmpi-dev \
openmpi-bin \
libblas-dev \
liblapack-dev \
&& rm -rf /var/lib/apt/lists/*

# Set petesc version
ENV PETSC_VERSION 3.7.2

# Install petsc opt
RUN cd /opt \
&& git clone --branch v$PETSC_VERSION --depth 1 https://bitbucket.org/petsc/petsc.git \
&& cd /opt/petsc \
&& wget https://bitbucket.org/likask/mofem-joseph/downloads/netcdf-4.3.3.1.tar.gz

RUN cd /opt/petsc \
&& ./configure \
--with-debugging=0 \
--with-mpi=1 \
--download-metis=1 \
--download-parmetis=1 \
--download-blacs=1 \
--download-hdf5=1 \
--download-netcdf=/opt/petsc/netcdf-4.3.3.1.tar.gz \
--with-shared-libraries=1 \
&& make PETSC_DIR=/opt/petsc PETSC_ARCH=arch-linux2-c-opt all \
&& rm -rvf /opt/petsc/arch-linux2-c-opt/externalpackages/*

# Install moab
RUN cd /opt \
&& git clone --branch master --depth 1  https://bitbucket.org/likask/moab.git

RUN cd /opt/moab \
&& autoreconf -fi \
&& ./configure \
--prefix=/opt/petsc/arch-linux2-c-opt \
--libdir=/opt/petsc/arch-linux2-c-opt/lib \
CC=mpicc CFLAGS="-fPIC -O" \
AR=/usr/bin/ar ARFLAGS=cr \
CXX=mpicxx CXXFLAGS="-fPIC" \
--disable-fortran \
--enable-shared --with-mpi= \
--with-hdf5=/opt/petsc/arch-linux2-c-opt \
--with-netcdf=/opt/petsc/arch-linux2-c-opt \
&& make install \
&& make clean

# Install boost
RUN cd /opt \
&& wget http://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.gz \
&& tar -xvzf boost_1_57_0.tar.gz \
&& cd /opt/boost_1_57_0 \
&& ./bootstrap.sh \
&& ./b2 install --prefix=/opt/petsc/arch-linux2-c-opt \
&& mv boost /opt/petsc/arch-linux2-c-opt/include/ \
&& cd /opt && rm -rvf /opt/boost_1_57_0*

RUN cd /opt \
&& wget https://cmake.org/files/v3.0/cmake-3.0.1-Darwin-universal.tar.gz \
&& tar -xzf cmake-3.0.1.tar.gz \
&& cd cmake-3.0.1 && cmake -DCMAKE_INSTALL_PREFIX=/opt/local \
&& make install \
&& cd /opt && rm -rvf cmake-3.0.1*

RUN sed -i 's/PATH.*/&\":\/opt\/petsc\/arch-linux2-c-opt\/bin\"/' /etc/environment
