FROM likask/mofem-intermidiate

LABEL maintainer="Lukasz.Kaczmarczyk@glasgow.ac.uk"

RUN apt-get update && \
  apt-get install -y \
  python3-pip \
  libgl1-mesa-glx \
  libglu1-mesa \
  xvfb \
  build-essential \
  python3-dev \
  npm \
  nodejs \
  libnode64 \
  && apt-get clean && rm -rf /var/lib/apt/lists/*  

RUN ln -s `which pip3.8` /usr/bin/pip3.8

RUN pip3 -q install pip --upgrade && \
  pip3 install \
  notebook==6.4.12 \
  jupyterhub==3.1.1 \
  jupyterhub-firstuseauthenticator && \
  npm install -g configurable-http-proxy

RUN pip3 install \
  pandas \
  scipy \
  gmsh \
  jupytext \
  pyvista==0.39.0 \
  pyvirtualdisplay \
  ipyvtklink \
  itkwidgets \
  ipywidgets==7.7 \
  pythreejs \
  ipyvtk-simple \
  panel \
  ipygany


RUN pip3 install \
  jupyter_contrib_nbextensions && \
  jupyter contrib nbextension install --sys-prefix && \
  jupyter nbextension install --py jupytext --sys-prefix && \
  jupyter nbextension enable --py jupytext --sys-prefix  && \
  jupyter nbextension enable equation-numbering/main && \
  jupyter nbextension enable splitcell/splitcell && \
  jupyter nbextension enable spellchecker/main && \
  jupyter nbextension enable collapsible_headings/main && \
  jupyter nbextension enable codefolding/main 

# allow jupyterlab for ipyvtk
ENV DISPLAY=:99.0
ENV JUPYTER_ENABLE_LAB=yes
ENV PYVISTA_USE_IPYVTK=true
ENV JUPYTER_TOKEN=mofem
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/site-packages/gmsh-4.8.3-Linux64-sdk/lib

WORKDIR $MOFEM_INSTALL_DIR

EXPOSE 8888
CMD /bin/bash -c "jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root"

