FROM likask/mofem-spack-mofem

LABEL maintainer="Lukasz.Kaczmarczyk@glasgow.ac.uk"

RUN . $MOFEM_ENV_FILE && \
  spack install mofem-softmech ^/$MOFEM_UM_HASH && \
  spack view symlink -i $MOFEM_INSTALL_DIR/um_view mofem-softmech

WORKDIR $MOFEM_INSTALL_DIR

# image run hook: the -l will make sure /etc/profile environments are loaded
CMD        /bin/bash -l

