FROM likask/mofem-spack-env:latest

LABEL maintainer="Lukasz.Kaczmarczyk@glasgow.ac.uk"

ENV MOFEM_SRC_DIR=$MOFEM_INSTALL_DIR/mofem-cephas
ENV MOFEM_UM_SRC_DIR=$MOFEM_SRC_DIR/mofem/users_modules

ADD . $MOFEM_SRC_DIR/

RUN . $SPACK_ROOT_DIR/share/spack/setup-env.sh && \
  spack dev-build \
  --source-path $MOFEM_SRC_DIR \
  --keep-prefix \
  --test root \
  mofem-cephas@develop~copy_user_modules build_type=RelWithDebInfo ^petsc+X && \
  MOFEM_CEPHAS_HASH=`spack find -lv mofem-cephas | awk '/mofem-cephas/ {print $1}' | head -n 1` && \
  echo "export MOFEM_CEPHAS_HASH=$MOFEM_CEPHAS_HASH" >> ~/.bashrc && \
  cd $MOFEM_SRC_DIR/spack-build-$MOFEM_CEPHAS_HASH && make clean

RUN . $SPACK_ROOT_DIR/share/spack/setup-env.sh && \
    MOFEM_CEPHAS_HASH=`spack find -lv mofem-cephas | awk '/mofem-cephas/ {print $1}' | head -n 1` && \
    spack dev-build \
    --test root  \
    --source-pat $MOFEM_UM_SRC_DIR \
    mofem-users-modules@develop build_type=RelWithDebInfo \
    ^/$MOFEM_CEPHAS_HASH && \
    MOFEM_UM_HASH=`spack find -lv mofem-users-modules | awk '/mofem-cephas/ {print $1}' | head -n 1` && \
    cd $MOFEM_UM_SRC_DIR/spack-build-$MOFEM_UM_HASH && make clean && \
    spack view symlink -i $MOFEM_INSTALL_DIR/um_view /$MOFEM_UM_HASH && \
    echo "export MOFEM_UM_HASH=$MOFEM_UM_HASH" >> ~/.bashrc && \
    echo "export PATH=$MOFEM_INSTALL_DIR/um_view:$PATH" >> ~/.bashrc

VOLUME $MOFEM_INSTALL_DIR
WORKDIR $MOFEM_INSTALL_DIR

# image run hook: the -l will make sure /etc/profile environments are loaded
CMD        /bin/bash -l



