FROM likask/mofem_build-pop-test-env:latest

MAINTAINER Lukasz.Kaczmarczyk@glasgow.ac.uk

ADD mofem /mofem
RUN /mofem/scripts/docker_build_core_lib_script.sh

RUN cd $MOFEM_INSTALL_DIR \
&& /opt/local/bin/cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=yes -DCMAKE_CXX_FLAGS="-Wall" users_modules \
&& make -j 4 && ctest --output-on-failure -D Experimental -R basic
RUN cd $MOFEM_INSTALL_DIR/basic_finite_elements/poisson && ctest -VV

WORKDIR $MOFEM_INSTALL_DIR/basic_finite_elements/poisson

CMD \
../../tools/mofem_part -my_file pop_test_mesh.cub -my_nparts 4 && \
mpirun -np 4 ./analytical_poisson_field_split -file_name out.h5m -order 4 -pc_type fieldsplit -ksp_atol 1e-8
