FROM likask/mofem-intermidiate

LABEL maintainer="Lukasz.Kaczmarczyk@glasgow.ac.uk"

ENV MOFEM_JUPYTER_HOME_DIR=/mofem_install/jupyter

ADD . $MOFEM_JUPYTER_HOME_DIR

# Install packages
RUN apt-get update && \
  apt-get install -y \
  sudo && \
  rm -rf /var/lib/apt/lists/*

RUN useradd mofem \
  -m -d /mofem_install/jupyter/mofem \
  -k /mofem_install/jupyter/skel/ \
  -p paN8aiEIonqJE && \
  usermod -aG sudo mofem

# Copy spack config
RUN cp -r ~/.spack /mofem_install/spack_config_dir && \ 
  chmod -R aug+rX /mofem_install/spack_config_dir && \
  chmod -R aug+rwX /mofem_install/spack && \
  chown -R mofem:mofem /mofem_install/mofem-cephas && \
  chown -R mofem:mofem /mofem_install/spack && \
  chown -R mofem:mofem /mofem_install/spack_config_dir && \
  chown -R mofem:mofem /mofem_install/core-* && \
  chown -R mofem:mofem /mofem_install/um-*

# Copy static styles for JupyterHub
RUN mkdir -p /usr/local/share/jupyterhub/static/css && \
  cp /mofem_install/jupyter/css/* /usr/local/share/jupyterhub/static/css

WORKDIR $MOFEM_INSTALL_DIR

EXPOSE 8000
CMD ["/bin/bash", "-c", "service ssh start;. ${MOFEM_ENV_FILE}; jupyterhub -f ${MOFEM_JUPYTER_HOME_DIR}/jupyterhub_config.py"]
