FROM likask/ubuntu_mofem:latest

MAINTAINER Lukasz.Kaczmarczyk@glasgow.ac.uk

ADD mofem /mofem

#RUN useradd -ms /bin/bash mofemuser
#RUN mkdir -p $MOFEM_ROOT_DIR \
#&& chown mofemuser $MOFEM_ROOT_DIR && chgrp mofemuser $MOFEM_ROOT_DIR \
#&& chown mofemuser $MOFEM_SRC_DIR && chgrp mofemuser $MOFEM_SRC_DIR
#USER mofemuser

RUN /mofem/scripts/docker_build_core_lib_script.sh
VOLUME /mofem_build
WORKDIR /mofem_build
CMD /mofem/scripts/docker_build_users_modules_script.sh
