set(GID_SOURCE_REPO "$ENV{HOME}/tmp/mofem/source")
set(CTEST_SOURCE_DIRECTORY "${GID_SOURCE_REPO}/mofem_v0.0.1")
set(CTEST_BINARY_DIRECTORY "$ENV{HOME}/tmp/mofem/build")

set(CTEST_PROJECT_NAME "MoFEM")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_CONFIGURATION "Release")
set(CTEST_BUILD_OPTIONS "-DCMAKE_CXX_FLAGS=-lstdc++ -DPETSC_DIR=/opt/build_for_gcc-mp-4.4/petsc-3.3-p3 -DPETSC_ARCH=arch-darwin-c-opt -DMOAB_DIR=/opt/build_for_gcc-mp-4.4/local-moab-4.6.0/ -DBUILD_SHARED_LIBS=FALSE -DCMAKE_CXX_COMPILER=/opt/build_for_gcc-mp-4.4/local/bin/mpicxx")

ctest_empty_binary_directory(${CTEST_BINARY_DIRECTORY})

find_program(CTEST_GIT_COMMAND NAMES git)
if(NOT EXISTS "${CTEST_SOURCE_DIRECTORY}")
  set(CTEST_CHECKOUT_COMMAND "${CTEST_GIT_COMMAND} clone https://likask@bitbucket.org/likask/mofem-joseph.git ${GID_SOURCE_REPO}")
else(EXISTS "${CTEST_SOURCE_DIRECTORY}")
  set(CTEST_CHECKOUT_COMMAND "${CTEST_GIT_COMMAND} pull")
endif()
set(CTEST_UPDATE_COMMAND "${CTEST_GIT_COMMAND}")

#set(CTEST_CONFIGURE_COMMAND "${CMAKE_COMMAND} -DCMAKE_BUILD_TYPE=Release ${CTEST_BUILD_OPTIONS}")
#set(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} \"${CTEST_SOURCE_DIRECTORY}\"")
set(CTEST_CONFIGURE_COMMAND "${CMAKE_COMMAND} -DCMAKE_BUILD_TYPE:STRING=${CTEST_BUILD_CONFIGURATION}")
set(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} ${CTEST_BUILD_OPTIONS}")
set(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} \"-G${CTEST_CMAKE_GENERATOR}\"")
set(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} \"${CTEST_SOURCE_DIRECTORY}\"")

# Perform the Nightly build
ctest_start("Nightly")
ctest_update(SOURCE "${GID_SOURCE_REPO}")
ctest_configure()
ctest_build()
ctest_test()
ctest_submit()
