# - Try to find MESHKIT

# If unset, try environment

if(NOT MESHKIT_DIR)
  set(MESHKIT_DIR $ENV{MESHKIT_DIR})
endif(NOT MESHKIT_DIR)

find_library(MESHKIT_LIBRARY NAMES MeshKit PATHS "${MESHKIT_DIR}/lib")
find_library(MESHKIT_ALGS_LIBRARY NAMES MKalgs PATHS "${MESHKIT_DIR}/lib")
find_library(MESHKIT_UTILS_LIBRARY NAMES MKutils PATHS "${MESHKIT_DIR}/lib")
find_library(MESHKIT_EMON_LIBRARY NAMES emon PATHS "${MESHKIT_DIR}/lib")

message(STATUS ${MESHKIT_LIBRARY})
message(STATUS ${MESHKIT_ALGS_LIBRARY})
message(STATUS ${MESHKIT_UTILS_LIBRARY})
message(STATUS ${MESHKIT_EMON_LIBRARY})

if(MESHKIT_ALGS_LIBRARY) 
  include_directories("${MESHKIT_DIR}/include")
endif(MESHKIT_ALGS_LIBRARY)




