option(NOT_PRECOMPILED_HEADRES "Do not use procompiled headers" OFF)
if(NOT NOT_PRECOMPILED_HEADRES)
  if(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION} VERSION_GREATER 3.0.0)
    if("${CMAKE_CXX_COMPILER_ID}" MATCHES ".*[Cc]lang" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
      set(PRECOMPILED_HEADRES ON)
    endif("${CMAKE_CXX_COMPILER_ID}" MATCHES ".*[Cc]lang" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
  endif(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION} VERSION_GREATER 3.0.0)
endif(NOT NOT_PRECOMPILED_HEADRES)

function(my_add_executable target source)
  if(PRECOMPILED_HEADRES)
    set_source_files_properties(${source} PROPERTIES COMPILE_FLAGS "-include ${PERCOMPILED_MOFEM_HEADER}")
  endif(PRECOMPILED_HEADRES)
  add_executable(${target} ${source})
  if(PRECOMPILED_HEADRES)
    add_dependencies(${target} MoFEM.hpp.pch_copy)
  endif(PRECOMPILED_HEADRES)
endfunction(my_add_executable)
